#!/bin/bash

#  The AUHPC Ministry of Line Alchemy | HPC Research Shell Tools
#  A collection of functions, methods, and boilerplate for AUHPC researchers
#  ----------------------------------------------------------------------------
#  wall | AUHPC research community graffiti

the auhpc admins were here! [07.07.23]

bradley wuz here
